import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {supabase} from './lib/supabase';
import './styles.css';
import {createLocalSession,isLocalSessionExpired} from './domain/session';
import {LOCAL_ACCOUNT,validateLocalCredentials} from './domain/auth';
type Reminder={id:string;title:string;type:'personal'|'birthday'|'food';next_occurrence_at:string|null;status:string};
function Auth({ready}:{ready:(id:string)=>void}){const [email,setEmail]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState('');function submit(e:React.FormEvent){e.preventDefault();if(validateLocalCredentials(email,password))ready(LOCAL_ACCOUNT.userId);else setError('Sai username hoặc mật khẩu')}return <main className="auth"><section className="card"><div className="eyebrow">SELF REMINDER</div><h1>Nhắc đúng lúc, sống nhẹ đầu.</h1><p className="muted">Sinh nhật, lịch cá nhân và hạn dùng thực phẩm — gửi thẳng vào Telegram.</p><form onSubmit={submit}><label>Username<input type="text" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="vinh"/></label><label>Mật khẩu<input type="password" minLength={8} required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<div className="error">{error}</div>}<button>Đăng nhập</button></form></section></main>}
function App({uid}:{uid:string}){const [items,setItems]=useState<Reminder[]>([]),[show,setShow]=useState(false),[title,setTitle]=useState(''),[type,setType]=useState<Reminder['type']>('personal'),[starts,setStarts]=useState('');async function load(){if(!supabase)return;const {data}=await supabase.from('reminders').select('id,title,type,next_occurrence_at,status').order('next_occurrence_at');setItems((data??[]) as Reminder[]);await supabase.rpc('touch_owner_activity')}useEffect(()=>{load()},[]);async function add(e:React.FormEvent){e.preventDefault();if(!supabase)return;const d=new Date(starts).toISOString();const r=await supabase.from('reminders').insert({owner_id:uid,title,type,starts_at:d,next_occurrence_at:d,source:'web'});if(!r.error){setShow(false);setTitle('');setStarts('');load()}}async function done(id:string){await supabase?.from('reminders').update({status:'completed'}).eq('id',id);load()}return <main className="shell"><header><div><div className="eyebrow">SELF REMINDER</div><h1>Lịch của bạn</h1></div><div className="actions"><button onClick={()=>setShow(true)}>＋ Thêm lịch</button><button className="ghost" onClick={()=>supabase?.auth.signOut()}>Thoát</button></div></header><section className="stats"><div><span>Đang hoạt động</span><strong>{items.filter(x=>x.status==='active').length}</strong></div><div><span>7 ngày tới</span><strong>{items.filter(x=>x.next_occurrence_at&&new Date(x.next_occurrence_at)<new Date(Date.now()+6048e5)).length}</strong></div><div><span>Kết nối</span><strong className="ok">Telegram</strong></div></section><section className="list"><h2>Lịch sắp tới</h2>{items.filter(x=>x.status==='active').map(x=><article className="reminder" key={x.id}><div className={'dot '+x.type}/><div className="detail"><strong>{x.title}</strong><span>{x.type==='birthday'?'Sinh nhật':x.type==='food'?'Thực phẩm':'Cá nhân'} · {x.next_occurrence_at&&new Date(x.next_occurrence_at).toLocaleString('vi-VN')}</span></div><button className="icon" onClick={()=>done(x.id)}>✓</button></article>)}{!items.length&&<div className="empty">Chưa có lịch. Tạo một lịch đầu tiên để bắt đầu.</div>}</section>{show&&<div className="modal"><form className="card" onSubmit={add}><h2>Thêm lịch</h2><label>Tiêu đề<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Ví dụ: Sinh nhật Lan"/></label><label>Loại<select value={type} onChange={e=>setType(e.target.value as Reminder['type'])}><option value="personal">Cá nhân</option><option value="birthday">Sinh nhật</option><option value="food">Thực phẩm</option></select></label><label>Thời gian<input type="datetime-local" required value={starts} onChange={e=>setStarts(e.target.value)}/></label><div className="actions"><button type="button" className="ghost" onClick={()=>setShow(false)}>Huỷ</button><button>Tạo lịch</button></div></form></div>}</main>}
function Root(){const [uid,setUid]=useState<string|null>(null);useEffect(()=>{const cached=localStorage.getItem('self-reminder-session');if(cached){try{const local=JSON.parse(cached);if(!isLocalSessionExpired(new Date(),local))setUid(local.userId);else localStorage.removeItem('self-reminder-session')}catch{localStorage.removeItem('self-reminder-session')}}},[]);return uid?<App uid={uid}/>:<Auth ready={id=>{localStorage.setItem('self-reminder-session',JSON.stringify(createLocalSession(id,new Date())));setUid(id)}}/>};createRoot(document.getElementById('root')!).render(<React.StrictMode><Root/></React.StrictMode>);
